# Generated by Django 4.0.4 on 2022-09-14 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comuna')),
                ('nombre_comuna', models.CharField(max_length=100, verbose_name='Nombre comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Perfil')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionForo',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Publicación')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria Publicación')),
                ('titulo', models.CharField(default='', max_length=1000, verbose_name='titulo')),
                ('fecha', models.DateField(default='', max_length=11)),
                ('hora', models.CharField(default='', max_length=9, verbose_name='Hora')),
                ('mensaje', models.CharField(max_length=1000, verbose_name='Mensaje')),
                ('cantRespuestas', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Region')),
                ('nombre_region', models.CharField(max_length=100, verbose_name='Nombre Region')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.comuna')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='', max_length=11)),
                ('hora', models.CharField(default='', max_length=9, verbose_name='Hora')),
                ('comentario', models.CharField(max_length=1000)),
                ('valoracion', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.publicacionforo')),
            ],
        ),
        migrations.AddField(
            model_name='publicacionforo',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PublicacionAdopcion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Publicación')),
                ('tipo_animal', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('edad', models.IntegerField()),
                ('comentario', models.CharField(max_length=500)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('img', models.CharField(blank=True, max_length=1000, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.region'),
        ),
        migrations.CreateModel(
            name='CitaTomada',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='', max_length=11)),
                ('hora', models.CharField(default='', max_length=5)),
                ('motivo_consulta', models.CharField(default='', max_length=1000)),
                ('estado', models.CharField(default='En Espera', max_length=20)),
                ('id_mascota', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota')),
                ('id_veterinario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='CitaDisponible',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(default='', max_length=11)),
                ('hora', models.CharField(default='', max_length=5)),
                ('actualizacion', models.CharField(default='', max_length=30)),
                ('id_veterinario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='CitaConcluida',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='', max_length=11)),
                ('hora', models.CharField(default='', max_length=5)),
                ('motivo_consulta', models.CharField(default='', max_length=1000)),
                ('tratamiento', models.CharField(default='No se registraron tratamientos.', max_length=600)),
                ('comentario', models.CharField(default='No se registraron comentarios.', max_length=1000)),
                ('valoracion', models.IntegerField(default=0)),
                ('duracion', models.CharField(default='?', max_length=9)),
                ('id_cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_mascota', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota')),
                ('id_veterinario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario')),
            ],
        ),
    ]
