# Generated by Django 4.0.3 on 2022-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaforo',
            name='cantRespuestas',
            field=models.IntegerField(default='0'),
        ),
    ]
