# Generated by Django 4.0.1 on 2022-04-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comuna')),
                ('nombre_comuna', models.CharField(max_length=100, verbose_name='Nombre comuna')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.region')),
            ],
        ),
    ]
