# Generated by Django 4.0.3 on 2022-07-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0002_respuestaforo_cantrespuestas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaforo',
            name='cantRespuestas',
        ),
        migrations.AddField(
            model_name='publicacionforo',
            name='cantRespuestas',
            field=models.IntegerField(default='0'),
        ),
    ]
