# Generated by Django 4.0.1 on 2022-04-27 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ModuloGeneral', '0002_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionAdopcion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Publicación')),
                ('tipo_animal', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionForo',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Publicación')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria Publicación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('mensaje', models.CharField(max_length=1000, verbose_name='Mensaje')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCita',
            fields=[
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ModuloGeneral.citamedica')),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('valoracion', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=1000)),
                ('valoracion', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.publicacionforo')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='citamedica',
            name='id_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='id_veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario'),
        ),
    ]
