# Generated by Django 4.0.1 on 2022-05-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0002_alter_usuario_comuna_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfil'),
        ),
    ]
