# Generated by Django 4.0.1 on 2022-04-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='id_perfil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfilusuario'),
            preserve_default=False,
        ),
    ]
