# Generated by Django 4.0.3 on 2022-05-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0004_alter_usuario_comuna_alter_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaDisponible',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.DateField()),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CitaTomada',
            fields=[
                ('id_cita_tomada', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.CharField(max_length=1000)),
                ('id_cita_disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.citadisponible')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota')),
            ],
        ),
        migrations.RemoveField(
            model_name='resultadocita',
            name='id_cita',
        ),
        migrations.RenameField(
            model_name='veterinario',
            old_name='id_cliente',
            new_name='id_centro',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='veterinario',
            name='tipo_atencion',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.CreateModel(
            name='CitaConcluida',
            fields=[
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ModuloGeneral.citatomada')),
                ('tratamiento', models.CharField(max_length=600)),
                ('comentario', models.CharField(max_length=1000)),
                ('valoracion', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CitaMedica',
        ),
        migrations.DeleteModel(
            name='ResultadoCita',
        ),
        migrations.AddField(
            model_name='citadisponible',
            name='id_veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario'),
        ),
    ]
