# Generated by Django 4.0.1 on 2022-04-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0004_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
