# Generated by Django 4.0.3 on 2022-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0005_citadisponible_citatomada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='estado',
            field=models.CharField(default='LIBRE', max_length=10),
        ),
    ]
