# Generated by Django 4.0.1 on 2022-05-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0005_alter_veterinario_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='id_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfil'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
