# Generated by Django 4.0.3 on 2022-05-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0006_alter_citadisponible_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citadisponible',
            name='estado',
        ),
    ]
