# Generated by Django 3.2.3 on 2022-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0006_auto_20220518_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='citadisponible',
            name='hora',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='citadisponible',
            name='fecha',
            field=models.DateField(),
        ),
    ]
