# Generated by Django 4.0.3 on 2022-05-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0007_remove_citadisponible_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaconcluida',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
