# Generated by Django 4.0.1 on 2022-04-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0007_alter_perfilusuario_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='id_perfil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfilusuario'),
        ),
    ]
