# Generated by Django 3.2.3 on 2022-05-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0007_auto_20220518_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='hora',
            field=models.TimeField(default='00:00'),
        ),
    ]
