# Generated by Django 4.0.1 on 2022-05-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0007_veterinario_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='mascotas')),
                ('id_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.publicacionadopcion')),
                ('id_mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota')),
            ],
        ),
    ]
