# Generated by Django 4.0.3 on 2022-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0008_alter_citaconcluida_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='hora',
            field=models.TimeField(),
        ),
    ]
