# Generated by Django 4.0.1 on 2022-04-28 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0008_alter_usuarioperfil_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='id_perfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='id_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfilusuario'),
        ),
    ]
