# Generated by Django 4.0.1 on 2022-06-08 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0009_mascota_img_delete_imagenmascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionadopcion',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
