# Generated by Django 4.0.1 on 2022-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0010_remove_usuarioperfil_id_perfil_usuarioperfil_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='perfil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
