# Generated by Django 4.0.1 on 2022-06-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0010_publicacionadopcion_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionadopcion',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
