# Generated by Django 4.0.1 on 2022-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0011_usuarioperfil_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='perfil',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
