# Generated by Django 4.0.1 on 2022-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0011_publicacionadopcion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='correo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
