# Generated by Django 3.2.3 on 2022-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0011_alter_citadisponible_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
