# Generated by Django 4.0.1 on 2022-06-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0012_alter_veterinario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='correo',
            field=models.CharField(max_length=50),
        ),
    ]
