# Generated by Django 3.2.3 on 2022-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0012_alter_citadisponible_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
