# Generated by Django 4.0.3 on 2022-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0012_alter_citadisponible_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='fecha',
            field=models.CharField(max_length=11),
        ),
    ]
