# Generated by Django 4.0.3 on 2022-05-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0013_alter_citadisponible_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citatomada',
            old_name='id_cita_tomada',
            new_name='id_cita',
        ),
        migrations.RemoveField(
            model_name='citatomada',
            name='id_cita_disponible',
        ),
        migrations.AddField(
            model_name='citaconcluida',
            name='fecha',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='citaconcluida',
            name='hora',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='citaconcluida',
            name='id_mascota',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota'),
        ),
        migrations.AddField(
            model_name='citaconcluida',
            name='id_veterinario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario'),
        ),
        migrations.AddField(
            model_name='citaconcluida',
            name='motivo_consulta',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='citatomada',
            name='fecha',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='citatomada',
            name='hora',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='citatomada',
            name='id_veterinario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario'),
        ),
        migrations.AlterField(
            model_name='citaconcluida',
            name='comentario',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='citaconcluida',
            name='id_cita',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citaconcluida',
            name='tratamiento',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='citadisponible',
            name='fecha',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='citadisponible',
            name='hora',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='citadisponible',
            name='id_veterinario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario'),
        ),
        migrations.AlterField(
            model_name='citatomada',
            name='id_mascota',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota'),
        ),
        migrations.AlterField(
            model_name='citatomada',
            name='motivo_consulta',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
