# Generated by Django 4.0.1 on 2022-06-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0013_alter_veterinario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionadopcion',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
