# Generated by Django 4.0.3 on 2022-05-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0014_rename_id_cita_tomada_citatomada_id_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citadisponible',
            name='actualizacion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
