# Generated by Django 3.2.3 on 2022-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0014_auto_20220518_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='tipo_atencion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
