# Generated by Django 4.0.3 on 2022-05-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0015_citadisponible_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='actualizacion',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
