# Generated by Django 3.2.3 on 2022-05-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0015_alter_veterinario_tipo_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinario',
            name='tipo_atencion',
        ),
    ]
