# Generated by Django 3.2.13 on 2022-05-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0016_remove_veterinario_tipo_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.CharField(max_length=1000)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.mascota')),
            ],
        ),
        migrations.RemoveField(
            model_name='citadisponible',
            name='id_veterinario',
        ),
        migrations.RemoveField(
            model_name='citatomada',
            name='id_cita_disponible',
        ),
        migrations.RemoveField(
            model_name='citatomada',
            name='id_mascota',
        ),
        migrations.RenameField(
            model_name='veterinario',
            old_name='id_centro',
            new_name='id_cliente',
        ),
        migrations.AddField(
            model_name='veterinario',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='id_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.perfil'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='valoracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResultadoCita',
            fields=[
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ModuloGeneral.citamedica')),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='CitaConcluida',
        ),
        migrations.DeleteModel(
            name='CitaDisponible',
        ),
        migrations.DeleteModel(
            name='CitaTomada',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='id_veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloGeneral.veterinario'),
        ),
    ]
