# Generated by Django 4.0.3 on 2022-05-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0021_alter_citadisponible_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citadisponible',
            name='actualizacion',
            field=models.CharField(default='', max_length=30),
        ),
    ]
