# Generated by Django 4.0.4 on 2022-05-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0022_alter_citadisponible_actualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacionforo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='respuestaforo',
            name='fecha',
        ),
    ]
