# Generated by Django 4.0.3 on 2022-05-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0027_remove_citatomada_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='citatomada',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
