# Generated by Django 4.0.3 on 2022-05-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0028_citatomada_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citatomada',
            name='estado',
        ),
    ]
