# Generated by Django 4.0.3 on 2022-05-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0029_remove_citatomada_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='citatomada',
            name='estado',
            field=models.CharField(default='En Espera', max_length=20),
        ),
    ]
