# Generated by Django 4.0.3 on 2022-05-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0032_alter_citatomada_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaconcluida',
            name='duracion',
            field=models.CharField(default='?', max_length=5),
        ),
    ]
