# Generated by Django 4.0.3 on 2022-06-09 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0033_citaconcluida_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaconcluida',
            name='id_cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citaconcluida',
            name='comentario',
            field=models.CharField(default='No se registraron comentarios...', max_length=1000),
        ),
        migrations.AlterField(
            model_name='citaconcluida',
            name='duracion',
            field=models.CharField(default='?', max_length=9),
        ),
        migrations.AlterField(
            model_name='citaconcluida',
            name='tratamiento',
            field=models.CharField(default='No se registraron tratamientos...', max_length=600),
        ),
    ]
