# Generated by Django 4.0.3 on 2022-06-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0034_citaconcluida_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaconcluida',
            name='comentario',
            field=models.CharField(default='No se registraron comentarios.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='citaconcluida',
            name='tratamiento',
            field=models.CharField(default='No se registraron tratamientos.', max_length=600),
        ),
    ]
