# Generated by Django 4.0.3 on 2022-06-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0035_alter_citaconcluida_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citatomada',
            name='fecha',
            field=models.DateField(default='', max_length=11),
        ),
    ]
