# Generated by Django 4.0.3 on 2022-06-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloGeneral', '0036_alter_citatomada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaconcluida',
            name='fecha',
            field=models.DateField(default='', max_length=11),
        ),
    ]
